[startup]
fullscreen = false
open_debugger = false
open_devtools = false

[preview_image]
name_save_behaviour = "auto_generated"

[directories.default_out_dir]
create_panel = ""
split_panel = ""
modify_panel = ""

[[inspect_panel.image_attributes]]
category = "general_info"
label = "General Info"
attributes = [
  "name",
  "width",
  "height",
  "format",
  "fsize_hr",
  "absolute_url",
  "creation_datetime",
  "modification_datetime",
  "comments",
  "has_transparency",
  "color_mode",
  "color_profile",
  "bit_depth",
  "exif",
  "is_animated"
]

[[inspect_panel.image_attributes]]
category = "animation_info"
label = "Animation Info"
attributes = [
  "frame_count",
  "average_delay",
  "delays_are_even",
  "delays",
  "fps",
  "loop_duration",
  "loop_count"
]
