[startup]
fullscreen = false
open_debugger = false
open_devtools = false

[inspect_panel.image_attributes]
animation_info = [
  "frame_count",
  "average_delay",
  "delays_are_even",
  "delays",
  "fps",
  "loop_duration",
  "loop_count"
]
general_info = [
  "name",
  "width",
  "height",
  "format",
  "fsize_hr",
  "absolute_url",
  "creation_datetime",
  "modification_datetime",
  "comments",
  "has_transparency",
  "color_mode",
  "color_profile",
  "bit_depth",
  "exif",
  "is_animated"
]
